import './About.svelte.css.proxy.js';
/* src/pages/About.svelte generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	append,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "../_snowpack/pkg/svelte/internal.js";

function create_fragment(ctx) {
	let h1;
	let header;
	let h2;
	let img0;
	let img0_src_value;
	let section;
	let img1;
	let img1_src_value;
	let article0;
	let p0;
	let img2;
	let img2_src_value;
	let article3;
	let article1;
	let img3;
	let img3_src_value;
	let p1;
	let p2;
	let article2;
	let p3;
	let p4;
	let img4;
	let img4_src_value;
	let article5;
	let aside;
	let article4;
	let p5;
	let p6;
	let p7;
	let p8;

	return {
		c() {
			h1 = element("h1");
			h1.textContent = "ABOUT";
			header = element("header");
			h2 = element("h2");
			h2.textContent = `${/*content*/ ctx[0][0]}`;
			img0 = element("img");
			section = element("section");
			img1 = element("img");
			article0 = element("article");
			p0 = element("p");
			p0.textContent = `${/*content*/ ctx[0][1]}  `;
			img2 = element("img");
			article3 = element("article");
			article1 = element("article");
			img3 = element("img");
			p1 = element("p");
			p1.textContent = `${/*content*/ ctx[0][2]}`;
			p2 = element("p");
			p2.textContent = `${/*content*/ ctx[0][3]}`;
			article2 = element("article");
			p3 = element("p");
			p3.textContent = `${/*content*/ ctx[0][4]}`;
			p4 = element("p");
			p4.textContent = `${/*content*/ ctx[0][5]}`;
			img4 = element("img");
			article5 = element("article");
			aside = element("aside");
			aside.innerHTML = `<img src="images/optimized/about_4.jpg" class="svelte-ct3smr"/><img src="images/optimized/about_4.jpg" class="svelte-ct3smr"/>`;
			article4 = element("article");
			p5 = element("p");
			p5.textContent = `${/*content*/ ctx[0][6]}`;
			p6 = element("p");
			p6.textContent = `${/*content*/ ctx[0][7]}`;
			p7 = element("p");
			p7.textContent = `${/*content*/ ctx[0][8]}`;
			p8 = element("p");
			p8.textContent = `${/*content*/ ctx[0][9]}`;
			attr(h1, "class", "svelte-ct3smr");
			attr(h2, "class", "underline svelte-ct3smr");
			attr(img0, "class", "background");
			if (img0.src !== (img0_src_value = "images/optimized/about_header.jpg")) attr(img0, "src", img0_src_value);
			attr(header, "class", "center overlay svelte-ct3smr");
			attr(img1, "class", "background svelte-ct3smr");
			if (img1.src !== (img1_src_value = "images/optimized/about_background.jpg")) attr(img1, "src", img1_src_value);
			attr(p0, "class", "svelte-ct3smr");
			if (img2.src !== (img2_src_value = "images/optimized/about_1.jpg")) attr(img2, "src", img2_src_value);
			attr(img2, "class", "svelte-ct3smr");
			attr(article0, "class", "grid two svelte-ct3smr");
			if (img3.src !== (img3_src_value = "images/optimized/about_2.jpg")) attr(img3, "src", img3_src_value);
			attr(img3, "class", "svelte-ct3smr");
			attr(p1, "class", "svelte-ct3smr");
			attr(p2, "class", "svelte-ct3smr");
			attr(article1, "class", "svelte-ct3smr");
			attr(p3, "class", "svelte-ct3smr");
			attr(p4, "class", "svelte-ct3smr");
			if (img4.src !== (img4_src_value = "images/optimized/about_3.jpg")) attr(img4, "src", img4_src_value);
			attr(img4, "class", "svelte-ct3smr");
			attr(article2, "class", "svelte-ct3smr");
			attr(article3, "class", "grid two svelte-ct3smr");
			attr(p5, "class", "svelte-ct3smr");
			attr(p6, "class", "svelte-ct3smr");
			attr(p7, "class", "svelte-ct3smr");
			attr(p8, "class", "svelte-ct3smr");
			attr(article4, "class", "svelte-ct3smr");
			attr(article5, "class", "grid two svelte-ct3smr");
			attr(section, "class", "center overlay svelte-ct3smr");
		},
		m(target, anchor) {
			insert(target, h1, anchor);
			insert(target, header, anchor);
			append(header, h2);
			append(header, img0);
			insert(target, section, anchor);
			append(section, img1);
			append(section, article0);
			append(article0, p0);
			append(article0, img2);
			append(section, article3);
			append(article3, article1);
			append(article1, img3);
			append(article1, p1);
			append(article1, p2);
			append(article3, article2);
			append(article2, p3);
			append(article2, p4);
			append(article2, img4);
			append(section, article5);
			append(article5, aside);
			append(article5, article4);
			append(article4, p5);
			append(article4, p6);
			append(article4, p7);
			append(article4, p8);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(h1);
			if (detaching) detach(header);
			if (detaching) detach(section);
		}
	};
}

function instance($$self) {
	const content = [
		"A selfless promoter of Bangladesh’s apparel industry, with an innate desire to change the game.",
		"Mr. Mostafiz Uddin is a visionary in the area of the sustainable apparel ecosystem in Bangladesh through his philosophy which evolved from his passion for social and environmental ethics. He is believed to be a game changer in the industry through the promotion of innovation and fashion disruption, which he sees as key to the future success of the Bangladesh apparel sector. He is a selfless promoter of the critical issues surrounding sustainable apparel which include responsible business, technology, innovation, circularity and transparency.",
		"\"I was born in the southern Bangladesh district of Chattogram (Chittagong), into a middle-class family. In many considerations, my childhood was just ordinary, except for the support from and relationship with my Mom. She was the one who inspired me to be ‘myself' and 'listen to my heart'. When other kids were being protected from the outside world, my mother encouraged me to go out and experience the world first-hand.",
		"I joined the Bangladesh scouts at the age of 11, where I quickly became a group Leader. This leadership role drove me to later form a cricket team which entered into the district cricket tournament. In 1991 I actively worked with Operation Sea Angel, the US-led, military disaster relief programme, in the aftermath of the cyclone which had devastated the southern coast of Bangladesh that year.",
		"Right after completing my Higher Secondary School in 1995, my father Mr. Moslem Uddin (who was my role model) passed away following a heart attack, leaving me, as I was the eldest son, as head of my family. After completion of my HSC I gained admittance to the University of Madras in India. Having secured my degree I returned home in 1999 and I met a USA citizen who requested that I join him in his endeavour to help the Bangladesh Ready-Made-Garment sector.",
		"I started my career in an apparel company as a trainee merchandiser in 1999. What I experienced in this role drove me to start my own business and open a buying house the same year.",
		"To make my dreams come true and to put into practice what I had in mind for the textile sector, I soon realised I needed to establish my own factory, with my standards and incorporating my vision for the future. This is what I did in 2009, when Denim Expert Ltd. was founded.",
		"After 2009 I invested time and energy into my plans to create trade-fairs and industry summits in Bangladesh, the likes of which had never been seen before in the region, with a view to help promote my country and our industry.",
		"I am now working on the next steps in the journey, for my country, my people, for the industry and for the well-being of workers across the world.",
		"Come and join me!\""
	];

	return [content];
}

class About extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default About;