// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = "@import url(\"https://fonts.googleapis.com/css2?family=Poppins\");header.svelte-1bvjlhm.svelte-1bvjlhm{grid-gap:0}@media(min-width: 601px){header.svelte-1bvjlhm.svelte-1bvjlhm{grid-template-columns:1fr 2fr}}header.svelte-1bvjlhm img.svelte-1bvjlhm{width:100%}@media(min-width: 601px){header.svelte-1bvjlhm img.svelte-1bvjlhm{height:80vh;object-fit:cover}}header.svelte-1bvjlhm article.svelte-1bvjlhm{position:relative;z-index:1;padding:0 1em}@media(min-width: 601px){header.svelte-1bvjlhm article.svelte-1bvjlhm{padding:0 7em}}header.svelte-1bvjlhm article img.svelte-1bvjlhm{position:absolute;top:0;z-index:-1}header.svelte-1bvjlhm article h5.svelte-1bvjlhm{font-size:1rem}header.svelte-1bvjlhm article h3.svelte-1bvjlhm{margin-top:1em;display:inline-block}header.svelte-1bvjlhm article h3.svelte-1bvjlhm:after{content:\"\";display:block;width:50%;height:0.25em;background:white;margin-top:0.5em}header.svelte-1bvjlhm article.svelte-1bvjlhm:after{content:\"\";position:absolute;top:0;left:0;width:100%;height:100%;background:rgba(45, 62, 134, 0.25);z-index:-1}section.svelte-1bvjlhm.svelte-1bvjlhm{position:relative;padding-bottom:2.5em}section.svelte-1bvjlhm .background.svelte-1bvjlhm{position:absolute;top:0;z-index:-1;height:100%;width:100%;object-fit:cover}section.svelte-1bvjlhm .grid.svelte-1bvjlhm{padding:1em}@media(min-width: 601px){section.svelte-1bvjlhm .grid.svelte-1bvjlhm{padding:2.5em}}section.svelte-1bvjlhm .grid p.svelte-1bvjlhm{text-align:center;font-size:1.5em}section.svelte-1bvjlhm article.svelte-1bvjlhm{background:rgba(211, 211, 211, 0.15);width:75%;margin:0 auto;padding:2.5em;text-align:center}";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}