import './News.svelte.css.proxy.js';
/* src/pages/News.svelte generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "../_snowpack/pkg/svelte/internal.js";

function create_fragment(ctx) {
	let div2;

	return {
		c() {
			div2 = element("div");
			div2.innerHTML = `<img class="background svelte-uggqs3" src="images/optimized/news_background.jpg"/><h1 class="svelte-uggqs3">NEWS</h1><div class="filters svelte-uggqs3"><a href="#" class="svelte-uggqs3">ALL</a><a href="#" class="svelte-uggqs3">VIDEO</a><a href="#" class="svelte-uggqs3">PRINT</a><a href="#" class="svelte-uggqs3">ONLINE</a></div><div class="grid three svelte-uggqs3"><img class="contact_background svelte-uggqs3" src="images/optimized/news_1.jpg"/><img class="contact_background svelte-uggqs3" src="images/optimized/news_2.jpg"/><img class="contact_background svelte-uggqs3" src="images/optimized/news_3.jpg"/></div>`;
			attr(div2, "class", "overlay svelte-uggqs3");
			attr(div2, "id", "news");
		},
		m(target, anchor) {
			insert(target, div2, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div2);
		}
	};
}

class News extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default News;