import './Home.svelte.css.proxy.js';
/* src/pages/Home.svelte generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "../_snowpack/pkg/svelte/internal.js";

function create_fragment(ctx) {
	let header;

	return {
		c() {
			header = element("header");
			header.innerHTML = `<div class="avatar"><img src="images/optimized/avatar.jpg" class="svelte-8ub2mz"/></div><div class="summary svelte-8ub2mz"><img src="images/optimized/summary.jpg" class="svelte-8ub2mz"/><article class="svelte-8ub2mz"><h5 class="svelte-8ub2mz">Denim is my true passion. From the early days in the industry, till today, I do emphasize on bringing my part to denim at all levels. I boldly invest time into denim-fabric, design, development and washing, enabling my team and clients to take advantage of this. Let me take you through a presentation of my denim-universe.</h5><h3 class="svelte-8ub2mz">MOSTAFIZ UDDIN</h3></article></div>`;
			attr(header, "class", "svelte-8ub2mz");
		},
		m(target, anchor) {
			insert(target, header, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(header);
		}
	};
}

class Home extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Home;